export enum Path {
  CONNECT_TO_REMOTE = "/connect_remote",
  CREATE_ENVIRONMENT = "/create_environment",
  DASHBOARD = "/dashboard",
  DOWNLOAD_DOCKER = "/download_docker",
  WAITING_DOCKER_START = "/waiting_docker_start",
  HOME = "/",
  INSTALL_DOCKER = "/install_docker",
  OVERVIEW = "/overview",
  RESTART_REQUIRED = "/restart_required",
  STARTING_XUD = "/starting_xud",
  TRADEHISTORY = "/tradehistory",
  WALLETS = "/wallets",
  INCOMPATIBLE_WSL_SETTINGS = "/incompatible_wsl_settings",
}
