name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: xud-ui-*.AppImage
          - os: windows-latest
            artifact_name: xud-ui*.exe
          - os: macos-latest
            artifact_name: xud-ui-*.dmg

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Upload Binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.artifact_name }}
          tag: ${{ github.ref }}
          prerelease: true
          file_glob: true
